version: '3'
services:
  customer_service:
    build:
      context: ./customer_service
      dockerfile: Dockerfile
    container_name: customer_service
    restart: unless-stopped
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/youverify_task
    ports:
      - 5000:5000
    
  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    container_name: order_service
    restart: unless-stopped
    environment:
      - PORT=5100
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/youverify_task?replicaSet=rs
      - CUSTOMER_SERVICE_URI=http://customer_service:5000/api/v1/customers
      - PRODUCT_SERVICE_URI=http://product_service:5300/api/v1/products
      - PAYMENT_SERVICE_URI=http://payment_service:5200/api/v1/payment
    ports:
      - 5100:5100

  payment_service:
    build:
      context: ./payment_service
      dockerfile: Dockerfile
    container_name: payment_service
    restart: unless-stopped
    environment:
      - PORT=5200
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/youverify_task
      - RABBITMQ_URI=amqp://guest:guest@host.docker.internal:5672
    ports:
      - 5200:5200

  product_service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    container_name: product_service
    restart: unless-stopped
    environment:
      - PORT=5300
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/youverify_task
    ports:
      - 5300:5300
 
  payment_worker:
    build:
      context: ./payment_worker
      dockerfile: Dockerfile
    container_name: payment_worker
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/youverify_task
      - RABBITMQ_URI=amqp://guest:guest@host.docker.internal:5672
    ports:
      - 5400:5400
